config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username, presence: true, 
                       uniqueness: true, 
                       length: { minimum: 3, maximum: 25 }
  
  validates :email, presence: true, 
                    uniqueness: true, 
                    length: { maximum: 105 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!session[:user_id]
  end

  def require_user
    if not logged_in?
      flash[:notice] = 'You should be logged in'
      redirect_to(root_path)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :check_user_belonging, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order('id DESC')
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was successfully created'
      redirect_to @article
    else 
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article is updated!'
      redirect_to @article
    else
      render 'edit' 
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = 'Article is deleted'
      redirect_to articles_path
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def check_user_belonging
    if (@article.user != current_user) and not current_user.admin? 
      flash[:notice] = "You can only change your own articles"
      redirect_to(article_path)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5).order('id DESC')
  end

  def new 
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "#{@category.name} category has been saved"
      redirect_to(category_path(@category))
    else
      flash[:error] = "Some error creating category"
      render "new"
    end 
  end

  def edit 
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category has been updated"
      redirect_to(categories_path)
    else
      flash[:alert] = "Can't update category" 
      render 'edit'
    end
  end

  private 
  
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can access this path"
      redirect_to(categories_path)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email]
    password = params[:session][:password]

    user = User.find_by(email: email)
    if user and user.authenticate(password)
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else
      flash.now[:alert] = 'Incorrect credentials'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new 
    @user = User.new
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit 
  end

  def update 
    if @user.update(users_params)
      flash[:notice] = 'Your account information is updated'
      redirect_to @user
    else 
      render 'edit'
    end
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:notice] = 'Welcome to the alpha blog, you have successfully signed up'
      redirect_to articles_path
    else
      render 'new'
    end 
  end

  def destroy 
    @user.destroy
    flash[:notice] = "#{@user.username} account is deleted"
    redirect_to(users_path)
  end

  private

  def users_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user 
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and not current_user.admin?
      flash[:alert] = "You can only edit your own account"
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 90})
    email_address = user.email
    hash = Digest::MD5.hexdigest(email_address)
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% if @articles.size > 0 %>
  <h1 class="text-center mt-4">Listing all articles</h1>
<% end %>
<div class="container articles">
  <% @articles.each do |article| %>
    <div class="row justify-content-center m-3">
      <div class="col-12">
        <div class="card text-center shadow">
          <div class="card-header">
            <span class="font-italic">
              By <%= article.user.username %>
            </span>
            <% if article.categories.any? %>
              <div class="mt-3"><%= render article.categories %></div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to article.title, article_path(article), class: 'title-link' %>
            </h5>
            <p class="card-text">
              <%= article.description %>
            </p>
            <%= link_to 'View', article_path(article), class: 'btn btn-outline-success' %>
            <% if logged_in? && (article.user == current_user or current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-info' %>
              <%= link_to 'Delete', article_path(article), class: 'btn btn-danger', method: :delete  %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>created <%= time_ago_in_words(article.created_at) %> ago |</small> edited
            <%= time_ago_in_words(article.updated_at) %> ago
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %> 
<%= form_with(model: @article, class: "shadow p-3 mb-5 bg-white rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :title, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :title, class: 'form-control shadow', placeholder: 'Title...' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :description, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_area :description, rows: 10, class: 'form-control shadow', placeholder: 'Description...' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :category, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.collection_select :category_ids, Category.all, :id, :name, { prompt: 'Select Category'}, { multiple: true, class: 'custom-select' } %>
    </div>
  </div>
  <div class="form-group row justify-content-center">
    <%= f.submit class: 'btn btn-outline-success btn-lg' %>
  </div>
<% end %>
<p class="text-info">
  <%= link_to '[Cancel and return to articles listing]', articles_path %>
</p>

app/views/articles/edit.html.erb
<h1 class="text-center mt-2">Edit article</h1>
<div class="container">
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-2">Articles index</h1>
<%= will_paginate(@articles, class: 'apple_pagination') %>
<div class="container articles">
    <% @articles.each do |article| %>
        <div class="row justify-content-center m-3">
            <div class="col-12 col-md-8">
                <div class="card text-center shadow">
                    <div class="card-header">
                        <span class="font-italic">
                          By <%= link_to article.user.username, article.user, class: 'user-link' %>
                        </span>
                        <% if article.categories.any? %>
                          <div class="mt-3"><%= render article.categories %></div>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= link_to article.title, article_path(article), class: 'title-link' %>
                        </h5>
                        <p class="card-text">
                            <%= article.description %>
                        </p>
                        <%= link_to 'View', article_path(article), class: 'btn btn-outline-success' %>
                        <% if logged_in? && (article.user == current_user or current_user.admin?) %>
                            <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-info' %>
                            <%= link_to 'Delete', article_path(article), class: 'btn btn-danger', method: :delete  %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>created <%= time_ago_in_words(article.created_at) %> ago |</small> edited
                        <%= time_ago_in_words(article.updated_at) %> ago
                    </div>
                </div>
            </div>
        </div>
        <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-2">New Article</h1>
<div class="container">
  <%= render 'form' %> 
</div>

app/views/articles/show.html.erb
<div class="container articles">
  <div class="row justify-content-center m-3">
    <div class="col-8">
      <div class="card text-center shadow">
        <div class="card-header">
          <span class="font-italic">
            By <%= @article.user.username %>
            <%= link_to gravatar_for(@article.user, size: 50), user_path(@article.user) %>
          </span>
          <% if @article.categories.any? %>
            <div class="mt-3"><%= render @article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= @article.title %>
          </h5>
          <div class="card-text text-left">
            <%= simple_format(@article.description) %>
          </div>
          <% if logged_in? && @article.user == current_user %>
            <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-info' %>
            <%= link_to 'Delete', article_path(@article), class: 'btn btn-danger', method: :delete  %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>created <%= time_ago_in_words(@article.created_at) %> ago |</small> edited
          <%= time_ago_in_words(@article.updated_at) %> ago
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-primary ml-1" %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-2">Edit Category</h1>
<div class="container">
  <%= render 'shared/errors', obj: @category %> 
  <%= form_with(model: @category, class: "shadow p-3 mb-5 bg-white rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :name, class: 'form-control shadow', placeholder: 'Enter name' %>
    </div>
  </div>
  <div class="form-group row justify-content-center">
    <%= f.submit class: 'btn btn-outline-success btn-lg' %>
  </div>
<% end %>
<p class="text-info">
  <%= link_to '[Cancel and return to articles listing]', articles_path %>
</p>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-2">Categories</h1>
  <% if @categories.size === 0 %>
  <h2 class="text-center mt-2">no categories yet</h1>
  <% end %>
<ul class="categories-list">
  <% @categories.each do |category| %>
    <li><%= link_to "#{category.name} #{category.articles.any? && pluralize(category.articles.count, 'category')}", category %></li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1 class="text-center mt-2">New Article</h1>
<div class="container">
  <%= render 'shared/errors', obj: @category %> 
  <%= form_with(model: @category, class: "shadow p-3 mb-5 bg-white rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :name, class: 'form-control shadow', placeholder: 'Enter name' %>
    </div>
  </div>
  <div class="form-group row justify-content-center">
    <%= f.submit class: 'btn btn-outline-success btn-lg' %>
  </div>
<% end %>
<p class="text-info">
  <%= link_to '[Cancel and return to articles listing]', articles_path %>
</p>
</div>

app/views/categories/show.html.erb
<h2 class="text-center m-4"><%= @category.name %></h2>
<div class="center">
  <%=  link_to "Edit category", edit_category_path(@category), class: "btn btn-primary btn-lg btn-block" %>
</div>
<%= will_paginate(@articles, class: 'apple_pagination') %>
<%= render 'articles/article' %>
<%= will_paginate(@articles, class: 'apple_pagination') %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3">
    <div class="container">
      <p>Copyright &copy; <%= link_to 'Website', 'https://www.linkedin.com/in/irakli-asatiani/' %><p>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand', id: 'logo' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Bloggers', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'New Article', new_article_path, class: 'dropdown-item' %>
            <%= link_to 'View Articles', articles_path, class: 'dropdown-item' %>
          </div>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              <%= "Admin" if current_user.admin? %> Profile [<%= current_user.username %>]
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'See your profile', user_path(current_user), class: 'dropdown-item' %>
              <%= link_to 'Edit profile', edit_user_path(current_user), class: 'dropdown-item' %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Create category', new_category_path, class: 'dropdown-item' %>
              <%= link_to 'View categories', categories_path, class: 'dropdown-item' %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: 'nav-link', method: :delete %>
          </li>
        <% else %>
          <% if not logged_in? %>
          <li class="nav-item">
            <%= link_to 'Signup', signup_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: 'nav-link' %>
          </li>
          <% end %>
        <% end %>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="page-content">
      <%= render 'layouts/navigation' %>
      <%= render 'shared/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/home.html.erb
<div class="container-fluid" id="home-container">
    <div class="jumbotron text-center text-danger">
      <h1 class="display-4">Hello, world!</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%= link_to 'Sign up', signup_path, class: "btn btn-lg bg-success text-white" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger is-dismissable" role="alert">
    <h4 class="alert-heading">Validation errors
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </h4>
      <% obj.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |key, message| %>
  <div class="<%= key == 'notice' ? 'alert-success' : 'alert-danger' %> alert is-dismissable" role="alert">
    <h4 class="alert-heading"><%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </h4>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %> 
<%= form_with(model: @user, class: "shadow p-3 mb-5 bg-white rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :username, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :username, class: 'form-control shadow' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :email, rows: 10, class: 'form-control shadow' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :password, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.password_field :password, rows: 10, class: 'form-control shadow', placeholder: 'Choose password' %>
    </div>
  </div>
  <div class="form-group row justify-content-center">
    <%= f.submit(@user.new_record? ? 'Sign up' : 'Update account', class: 'btn btn-outline-success btn-lg') %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center mt-2">Edit user</h1>
<div class="container">
  <%= render 'form', obj: @user %> 
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-2">Alpha Bloggers</h1>
<div class="container articles">
  <% @users.each do |user| %>
    <div class="row justify-content-center m-3">
      <div class="col-12">
        <div class="card text-center shadow">
          <div class="card-header">
            <span class="text-capitalize text-info">
              <%= user.username %>
            </span>
          </div>
          <div class="card-body">
            <p class="card-text">
              <%= gravatar_for user, size: 200 %>
              <%= user.articles.blank? ? "has no articles yet" : "#{user.articles.size} articles" %>
            </p>
            <%= link_to 'View', user_path(user), class: 'btn btn-outline-success' %>
            <% if logged_in? && user == current_user %>
              <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-info' %>
            <% end %>
            <% if current_user.admin? %>
              <%=  link_to 'Delete', user_path(user), method: :delete, class: 'btn btn-outline-danger', data: { confirm: "Are you sure?" }  %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-2">Signup</h1>
<div class="container">
  <%= render 'form', obj: @user %> 
</div>

app/views/users/show.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile'</h1>
<%= gravatar_for @user, size: 200 %>
<div class="mt-3">
  <%= will_paginate(@articles, class: 'apple_pagination') %>
</div>
<%= render 'articles/article' %>